server:
  port: 8081
spring:
  datasource:
    username: josef
    password:
    url: jdbc:h2:mem:recipe-mxl
  #    internacionalization
  messages:
    basename: messages/messages
    fallback-to-system-locale: false
  web:
    locale: en
    locale-resolver: fixed
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true